### ISSUE TITLE
Accordion/Collapsible arrow overlaps text

### ISSUE THREAD

**Issue by mckenziewest** [oel-mediateam/droplets-for-canvas#3]
Padding should be added so that the arrow does not overlap the text.

![image](https://user-images.githubusercontent.com/20980506/187533339-211f0e36-e345-4174-b92a-2c33ae76895d.png)

**Comment by Lin87** [comment]
Hello, thank you for your feedback, and sorry for the delay. The fix is available in the latest version 3.2.9. Contact your Canvas Admin to update the Droplets in Canvas. Here are the instructions to update Droplets in Canvas: https://docs.google.com/document/d/1dBi1zytQTKb-g9nYff6hmPXMlSGeSM3qGdrF2eeAOv8/edit?usp=sharing.

**Comment by mckenziewest** [comment]
Thanks for making this change!
